### ISSUE TITLE
switch cargo init crate type to lib and specify necessary lib properties

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-cmd#23]
Add
```toml
[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
```

to default `Cargo.toml` file. Also, change crate type to lib

As discussed here: https://github.com/holochain/holochain-cmd/pull/20#pullrequestreview-150559277
